# Generated by Django 5.1.7 on 2025-03-16 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('itemID', models.AutoField(primary_key=True, serialize=False)),
                ('itemName', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('dateReported', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(max_length=255)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='item_photos/')),
                ('status', models.CharField(choices=[('Lost', 'Lost'), ('Found', 'Found')], default='Lost', max_length=10)),
                ('contactInfo', models.CharField(max_length=255)),
            ],
        ),
    ]
