# Generated by Django 5.1.7 on 2025-03-24 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lostfound', '0002_alter_item_dateclaimed_alter_item_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='contactInfo',
            field=models.CharField(max_length=255, verbose_name='Contact Information'),
        ),
        migrations.AlterField(
            model_name='item',
            name='dateClaimed',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date Claimed'),
        ),
        migrations.AlterField(
            model_name='item',
            name='dateReported',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Reported'),
        ),
        migrations.AlterField(
            model_name='item',
            name='itemName',
            field=models.CharField(max_length=255, verbose_name='Item Name'),
        ),
        migrations.AlterField(
            model_name='item',
            name='proofOfOwnership',
            field=models.TextField(blank=True, null=True, verbose_name='Proof of Ownership'),
        ),
    ]
