# Generated by Django 5.1.7 on 2025-03-29 00:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lostfound', '0003_alter_item_contactinfo_alter_item_dateclaimed_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Report',
            new_name='itemReport',
        ),
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('Lost', 'Lost'), ('Found', 'Found'), ('Under Review', 'Under Review'), ('Claimed', 'Claimed')], default='Lost', max_length=20),
        ),
        migrations.CreateModel(
            name='claimRequestReport',
            fields=[
                ('claimID', models.AutoField(primary_key=True, serialize=False)),
                ('proofOfOwnership', models.TextField(verbose_name='Proof of Ownership')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('dateSubmitted', models.DateTimeField(auto_now_add=True, verbose_name='Date Submitted')),
                ('dateReviewed', models.DateTimeField(blank=True, null=True, verbose_name='Date Reviewed')),
                ('claimer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claimUser', to=settings.AUTH_USER_MODEL)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lostfound.item')),
                ('reviewAdmin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimAdminUser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='fraudClaimReport',
            fields=[
                ('fraudID', models.AutoField(primary_key=True, serialize=False)),
                ('proofOfOwnership', models.TextField(verbose_name='Proof of Ownership')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Resolved', 'Resolved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('dateSubmitted', models.DateTimeField(auto_now_add=True)),
                ('dateReviewed', models.DateTimeField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lostfound.item')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportUser', to=settings.AUTH_USER_MODEL)),
                ('reviewAdmin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportAdminUser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
