# Generated by Django 5.1.7 on 2025-03-29 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lostfound', '0004_rename_report_itemreport_alter_item_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='claimrequestreport',
            options={'verbose_name': 'Claim Requests'},
        ),
        migrations.AlterModelOptions(
            name='fraudclaimreport',
            options={'verbose_name': 'Fraudulent Claims'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'Lost and Found Items'},
        ),
    ]
