# Generated by Django 5.1.7 on 2025-03-31 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lostfound', '0005_alter_claimrequestreport_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='claimrequestreport',
            options={'verbose_name': 'Claim Request'},
        ),
        migrations.AlterModelOptions(
            name='fraudclaimreport',
            options={'verbose_name': 'Fraudulent Claim'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'Lost and Found Item'},
        ),
        migrations.AddField(
            model_name='claimrequestreport',
            name='contactInfo',
            field=models.CharField(default='Not Provided', max_length=255, verbose_name='Contact Information'),
        ),
        migrations.AddField(
            model_name='fraudclaimreport',
            name='contactInfo',
            field=models.CharField(default='Not Provided', max_length=255, verbose_name='Contact Information'),
        ),
        migrations.AlterField(
            model_name='claimrequestreport',
            name='proofOfOwnership',
            field=models.TextField(default='Not Provided', verbose_name='Proof of Ownership'),
        ),
        migrations.AlterField(
            model_name='fraudclaimreport',
            name='proofOfOwnership',
            field=models.TextField(default='Not Provided', verbose_name='Proof of Ownership'),
        ),
        migrations.AlterField(
            model_name='item',
            name='contactInfo',
            field=models.CharField(default='Not Provided', max_length=255, verbose_name='Contact Information'),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, default='Not Provided', null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='itemName',
            field=models.CharField(default='Not Provided', max_length=255, verbose_name='Item Name'),
        ),
        migrations.AlterField(
            model_name='item',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='itemReport',
        ),
    ]
